version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /api/node_modules
      - ./api:/api
    environment:
    # both hosts here are refences to the services respectively
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgrespassword
      - PGPORT=5432
  client:
    environment:
      - WDS_SOCKET_PORT=0
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /client/node_modules
      - ./client:/client
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /worker/node_modules
      - ./worker:/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
